### ISSUE TITLE
使用校外方法连接不上

### ISSUE THREAD

**Issue by gogongxt** [Mythologyli/websocket-via-webvpn#1]
你好，我现在成功编译了代码并添加了config文件，并且成功连接上了：
![image](https://github.com/Mythologyli/websocket-via-webvpn/assets/47113549/c0acb14b-010c-4b06-9546-cd7047f0c931)
然后我新开一个终端，设置代理变量，但是ping不到我校内的电脑，ssh也连不上（正常如果我在校内用校园网是可以ping到和ssh连接上的）
![image](https://github.com/Mythologyli/websocket-via-webvpn/assets/47113549/a61f0e25-715a-4e0f-8e45-3c570d27c748)

**Comment by Mythologyli** [comment]
首先你要在校内建好 v2ray server 才行，我看你截图上还是默认地址，无法生效的

ping 不了是正常的，ICMP 不能代理

ssh 的话仅仅用环境变量走不了代理，可以自已搜一搜教程

**Comment by gogongxt** [comment]
这样的啊
我换了一个方法，看了大佬的帖子http://cc98.org/topic/5741861
使用tun模式试了一下，可以用来浏览器访问98，但是仍然不能ssh，我用的是22端口，请问是不能用22端口还是我哪里别的操作有问题。

**Comment by Mythologyli** [comment]
RVPN 禁用了 22 端口，需要修改服务器 SSH 端口
